package api

import (
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/lichti/zaplab/internal/whatsapp"
	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
)

// ── package-level state ──────────────────────────────────────────────────────

var (
	waDB        *sql.DB    // read-only connection to whatsapp.db
	waDBWrite   *sql.DB    // read-write connection to whatsapp.db
	dbFilePath  string     // absolute path to the .db file (no params)
	dbBackupDir string     // directory where backups are stored
	dbMu        sync.Mutex // guards backup/restore operations
)

// allowedTables is the hard-coded allowlist. Any name not in this list → 404.
var allowedTables = []string{
	"whatsmeow_device",
	"whatsmeow_identity_keys",
	"whatsmeow_pre_keys",
	"whatsmeow_sessions",
	"whatsmeow_sender_keys",
	"whatsmeow_app_state_sync_keys",
	"whatsmeow_app_state_version",
	"whatsmeow_app_state_mutation_macs",
	"whatsmeow_contacts",
	"whatsmeow_chat_settings",
	"whatsmeow_message_secrets",
	"whatsmeow_privacy_tokens",
}

var tableDescriptions = map[string]string{
	"whatsmeow_device":                  "Device identity: JID, Noise key, Identity key, Signed pre-key, Registration ID, platform, and server token. The core cryptographic identity of this WhatsApp session.",
	"whatsmeow_identity_keys":           "Signal Protocol identity keys for each known JID/device pair. Used to verify the long-term identity of contacts and detect security code changes.",
	"whatsmeow_pre_keys":                "One-time pre-keys generated by this device for Signal session initiation (X3DH key agreement). Each is consumed exactly once when a new session is established.",
	"whatsmeow_sessions":                "Signal Protocol Double Ratchet session state per contact/device. Contains serialized session data including chain keys, message keys, and ratchet counters.",
	"whatsmeow_sender_keys":             "Group SenderKey Distribution records. Each group member distributes a sender key so others can decrypt their messages without per-message key exchange.",
	"whatsmeow_app_state_sync_keys":     "Symmetric keys used to decrypt app state patches (contacts, settings, starred messages, labels, etc.) synced from the WhatsApp server.",
	"whatsmeow_app_state_version":       "Current version index and hash of each app state collection (critical, regular, critical_unblock_to_primary, etc.). Used for incremental sync.",
	"whatsmeow_app_state_mutation_macs": "HMAC integrity codes for individual app state mutations stored in the Merkle tree. Used to verify patch integrity during app state sync.",
	"whatsmeow_contacts":                "Known contacts with their push names and full names as synced from the WhatsApp server.",
	"whatsmeow_chat_settings":           "Per-conversation settings: mute expiry timestamp, pinned status, archived status.",
	"whatsmeow_message_secrets":         "Per-message secrets for media decryption and ephemeral (view-once) message handling.",
	"whatsmeow_privacy_tokens":          "Privacy tokens used when checking if phone numbers are registered on WhatsApp (contact availability check).",
}

// ── init ─────────────────────────────────────────────────────────────────────

// initDBExplorer opens read-only and read-write SQL connections to the whatsmeow
// SQLite file. Only supported when dialect is "sqlite". Called once from api.Init.
func initDBExplorer(dsn, dialect string) error {
	if dialect != "sqlite" {
		pb.Logger().Warn("DB Explorer: only supported for sqlite dialect — skipping")
		return nil
	}
	if dsn == "" {
		pb.Logger().Warn("DB Explorer: empty DSN — skipping")
		return nil
	}

	dbFilePath = extractFilePath(dsn)

	// Read-only connection (for queries)
	roDSN := filePathToDSN(dbFilePath, "ro")
	db, err := sql.Open("sqlite", roDSN)
	if err != nil {
		return fmt.Errorf("db explorer: open read-only connection: %w", err)
	}
	db.SetMaxOpenConns(1)
	waDB = db

	// Read-write connection (for edits and VACUUM INTO backups)
	rwDSN := filePathToDSN(dbFilePath, "rwc")
	dbw, err := sql.Open("sqlite", rwDSN)
	if err != nil {
		return fmt.Errorf("db explorer: open read-write connection: %w", err)
	}
	dbw.SetMaxOpenConns(1)
	waDBWrite = dbw

	// Backup directory inside PocketBase data dir
	dbBackupDir = filepath.Join(pb.DataDir(), "db_backups")
	if err := os.MkdirAll(dbBackupDir, 0o750); err != nil {
		pb.Logger().Warn("DB Explorer: could not create backup dir", "error", err)
	}

	pb.Logger().Info("DB Explorer: connections established", "file", dbFilePath, "backups", dbBackupDir)
	return nil
}

// extractFilePath strips the file: prefix and query params from a SQLite DSN.
// "file:/path/to/db?params" → "/path/to/db"
func extractFilePath(dsn string) string {
	p := strings.TrimPrefix(dsn, "file:")
	if idx := strings.Index(p, "?"); idx >= 0 {
		p = p[:idx]
	}
	return p
}

// filePathToDSN builds a file URI DSN with the given mode (ro, rw, rwc).
func filePathToDSN(path, mode string) string {
	return fmt.Sprintf("file:%s?mode=%s", path, mode)
}

// ── helpers ───────────────────────────────────────────────────────────────────

func isAllowedTable(name string) bool {
	for _, t := range allowedTables {
		if t == name {
			return true
		}
	}
	return false
}

// dbeCheckDB returns a ServiceUnavailable error response if connections are not ready.
func dbeCheckDB(e *core.RequestEvent) bool {
	return waDB != nil && waDBWrite != nil
}

// dbeTableColumns returns the ordered list of column names for table via PRAGMA.
func dbeTableColumns(table string) ([]string, error) {
	rows, err := waDB.Query(fmt.Sprintf("PRAGMA table_info(%q)", table))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []string
	for rows.Next() {
		var cid int
		var name, typ string
		var notNull int
		var dfltVal sql.NullString
		var pk int
		if err := rows.Scan(&cid, &name, &typ, &notNull, &dfltVal, &pk); err != nil {
			return nil, err
		}
		cols = append(cols, name)
	}
	return cols, rows.Err()
}

// dbeTableColumnTypes returns column name→SQLite type affinity map.
func dbeTableColumnTypes(table string) (map[string]string, error) {
	rows, err := waDB.Query(fmt.Sprintf("PRAGMA table_info(%q)", table))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	types := make(map[string]string)
	for rows.Next() {
		var cid int
		var name, typ string
		var notNull int
		var dfltVal sql.NullString
		var pk int
		if err := rows.Scan(&cid, &name, &typ, &notNull, &dfltVal, &pk); err != nil {
			return nil, err
		}
		types[name] = strings.ToUpper(typ)
	}
	return types, rows.Err()
}

// dbeFilterClause builds a safe WHERE clause from a free-text filter.
// The filter value is passed exclusively as a bound parameter.
func dbeFilterClause(cols []string, filter string) (string, []any) {
	if filter == "" {
		return "", nil
	}
	like := "%" + filter + "%"
	parts := make([]string, len(cols))
	args := make([]any, len(cols))
	for i, col := range cols {
		parts[i] = fmt.Sprintf(`CAST("%s" AS TEXT) LIKE ?`, col)
		args[i] = like
	}
	return "WHERE (" + strings.Join(parts, " OR ") + ")", args
}

// dbeScanRows scans all rows into [][]any. []byte blobs are hex-encoded.
// When withRowID is true the first column scanned is the rowid.
func dbeScanRows(rows *sql.Rows, numCols int) ([][]any, error) {
	var result [][]any
	for rows.Next() {
		ptrs := make([]any, numCols)
		vals := make([]any, numCols)
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return nil, err
		}
		row := make([]any, numCols)
		for i, v := range vals {
			if b, ok := v.([]byte); ok {
				row[i] = hex.EncodeToString(b)
			} else {
				row[i] = v
			}
		}
		result = append(result, row)
	}
	return result, rows.Err()
}

// ── read endpoints ────────────────────────────────────────────────────────────

// getDBTables returns the allowed whatsmeow tables with descriptions and row counts.
func getDBTables(e *core.RequestEvent) error {
	if !dbeCheckDB(e) {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{
			"error": "DB Explorer not available (sqlite only or not yet initialised)",
		})
	}
	type tableInfo struct {
		Name        string `json:"name"`
		Description string `json:"description"`
		Count       int64  `json:"count"`
	}
	tables := make([]tableInfo, 0, len(allowedTables))
	for _, t := range allowedTables {
		var count int64
		_ = waDB.QueryRow(fmt.Sprintf("SELECT COUNT(*) FROM %q", t)).Scan(&count)
		tables = append(tables, tableInfo{
			Name:        t,
			Description: tableDescriptions[t],
			Count:       count,
		})
	}
	return e.JSON(http.StatusOK, map[string]any{"tables": tables})
}

// getDBTable returns paginated rows for a single allowed table.
// Rows include "_rowid_" as the first column for edit/delete operations.
// Query params: page (1-based), limit (1-200, default 50), filter (text search).
func getDBTable(e *core.RequestEvent) error {
	if !dbeCheckDB(e) {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{
			"error": "DB Explorer not available",
		})
	}
	table := e.Request.PathValue("table")
	if !isAllowedTable(table) {
		return apis.NewNotFoundError("Table not found", nil)
	}

	page, _ := strconv.Atoi(e.Request.URL.Query().Get("page"))
	if page < 1 {
		page = 1
	}
	limit, _ := strconv.Atoi(e.Request.URL.Query().Get("limit"))
	if limit < 1 || limit > 200 {
		limit = 50
	}
	filter := e.Request.URL.Query().Get("filter")

	cols, err := dbeTableColumns(table)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	colTypes, err := dbeTableColumnTypes(table)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	if len(cols) == 0 {
		return e.JSON(http.StatusOK, map[string]any{
			"table": table, "columns": []string{}, "types": []string{},
			"rows": []any{}, "page": 1, "limit": limit, "total": 0, "pages": 0,
		})
	}

	whereClause, filterArgs := dbeFilterClause(cols, filter)

	var total int64
	countSQL := fmt.Sprintf("SELECT COUNT(*) FROM %q %s", table, whereClause)
	if err := waDB.QueryRow(countSQL, filterArgs...).Scan(&total); err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}

	offset := (page - 1) * limit
	// Always select rowid as first column so the frontend can target specific rows for edits.
	selectSQL := fmt.Sprintf(`SELECT rowid AS _rowid_, * FROM %q %s LIMIT ? OFFSET ?`, table, whereClause)
	args := append(filterArgs, limit, offset)
	rows, err := waDB.Query(selectSQL, args...)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	defer rows.Close()

	allCols := append([]string{"_rowid_"}, cols...)
	data, err := dbeScanRows(rows, len(allCols))
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}

	// Build ordered type list matching allCols (rowid is INTEGER)
	typeList := make([]string, len(allCols))
	typeList[0] = "INTEGER"
	for i, c := range cols {
		typeList[i+1] = colTypes[c]
	}

	pages := int(math.Ceil(float64(total) / float64(limit)))
	return e.JSON(http.StatusOK, map[string]any{
		"table":   table,
		"columns": allCols,
		"types":   typeList,
		"rows":    data,
		"page":    page,
		"limit":   limit,
		"total":   total,
		"pages":   pages,
	})
}

// ── write endpoints ───────────────────────────────────────────────────────────

// patchDBTableRow updates specific columns of a single row identified by rowid.
// Creates an automatic backup before applying the change.
// Body: {"values": {"col": "val"}, "reconnect": true|false}
func patchDBTableRow(e *core.RequestEvent) error {
	if !dbeCheckDB(e) {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{"error": "DB Explorer not available"})
	}
	table := e.Request.PathValue("table")
	if !isAllowedTable(table) {
		return apis.NewNotFoundError("Table not found", nil)
	}
	rowid, err := strconv.ParseInt(e.Request.PathValue("rowid"), 10, 64)
	if err != nil {
		return apis.NewBadRequestError("invalid rowid", nil)
	}

	var req struct {
		Values    map[string]any `json:"values"`
		Reconnect bool           `json:"reconnect"`
	}
	if err := json.NewDecoder(e.Request.Body).Decode(&req); err != nil {
		return apis.NewBadRequestError("invalid JSON body", err)
	}
	if len(req.Values) == 0 {
		return apis.NewBadRequestError("values map is empty", nil)
	}

	// Validate all column names against the table schema
	tableCols, err := dbeTableColumns(table)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	colTypes, err := dbeTableColumnTypes(table)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	allowed := make(map[string]bool, len(tableCols))
	for _, c := range tableCols {
		allowed[c] = true
	}
	for col := range req.Values {
		if !allowed[col] {
			return apis.NewBadRequestError(fmt.Sprintf("unknown column: %s", col), nil)
		}
	}

	// Create automatic backup before any write
	dbMu.Lock()
	backupName, backupErr := dbeCreateBackup()
	dbMu.Unlock()
	if backupErr != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{
			"error": fmt.Sprintf("backup failed before write: %v", backupErr),
		})
	}

	// Build SET clause (column names are validated, values are bound params)
	setClauses := make([]string, 0, len(req.Values))
	setArgs := make([]any, 0, len(req.Values))
	for col, val := range req.Values {
		setClauses = append(setClauses, fmt.Sprintf(`"%s" = ?`, col))
		// For BLOB columns, accept hex string from the UI and decode to bytes
		if strings.Contains(colTypes[col], "BLOB") {
			if s, ok := val.(string); ok {
				if decoded, hexErr := hex.DecodeString(s); hexErr == nil {
					val = decoded
				}
				// else: store as string — let the user learn from the result
			}
		}
		setArgs = append(setArgs, val)
	}
	setArgs = append(setArgs, rowid)
	updateSQL := fmt.Sprintf(`UPDATE %q SET %s WHERE rowid = ?`, table, strings.Join(setClauses, ", "))

	if _, err := waDBWrite.Exec(updateSQL, setArgs...); err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}

	if req.Reconnect {
		if err := whatsapp.ForceReconnect(); err != nil {
			return e.JSON(http.StatusOK, map[string]any{
				"message":         "row updated but reconnect failed",
				"backup":          backupName,
				"reconnect":       false,
				"reconnect_error": err.Error(),
			})
		}
	}

	return e.JSON(http.StatusOK, map[string]any{
		"message":   "row updated",
		"backup":    backupName,
		"reconnect": req.Reconnect,
	})
}

// deleteDBTableRow deletes a single row identified by rowid.
// Creates an automatic backup before deleting.
// Body: {"reconnect": true|false}
func deleteDBTableRow(e *core.RequestEvent) error {
	if !dbeCheckDB(e) {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{"error": "DB Explorer not available"})
	}
	table := e.Request.PathValue("table")
	if !isAllowedTable(table) {
		return apis.NewNotFoundError("Table not found", nil)
	}
	rowid, err := strconv.ParseInt(e.Request.PathValue("rowid"), 10, 64)
	if err != nil {
		return apis.NewBadRequestError("invalid rowid", nil)
	}

	var req struct {
		Reconnect bool `json:"reconnect"`
	}
	// Body is optional — default reconnect=false
	_ = json.NewDecoder(e.Request.Body).Decode(&req)

	dbMu.Lock()
	backupName, backupErr := dbeCreateBackup()
	dbMu.Unlock()
	if backupErr != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{
			"error": fmt.Sprintf("backup failed before delete: %v", backupErr),
		})
	}

	deleteSQL := fmt.Sprintf(`DELETE FROM %q WHERE rowid = ?`, table)
	res, err := waDBWrite.Exec(deleteSQL, rowid)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	affected, _ := res.RowsAffected()
	if affected == 0 {
		return apis.NewNotFoundError("row not found", nil)
	}

	if req.Reconnect {
		if err := whatsapp.ForceReconnect(); err != nil {
			return e.JSON(http.StatusOK, map[string]any{
				"message":         "row deleted but reconnect failed",
				"backup":          backupName,
				"reconnect":       false,
				"reconnect_error": err.Error(),
			})
		}
	}

	return e.JSON(http.StatusOK, map[string]any{
		"message":   "row deleted",
		"backup":    backupName,
		"reconnect": req.Reconnect,
	})
}

// postDBReconnect triggers a WhatsApp reconnect (disconnect + connect).
// Body: {"full": false} — if true, tears down and rebuilds the full whatsmeow stack.
func postDBReconnect(e *core.RequestEvent) error {
	var req struct {
		Full bool `json:"full"`
	}
	_ = json.NewDecoder(e.Request.Body).Decode(&req)

	var err error
	if req.Full {
		err = whatsapp.Reinitialize()
	} else {
		err = whatsapp.ForceReconnect()
	}
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	mode := "reconnect"
	if req.Full {
		mode = "full reinitialize"
	}
	return e.JSON(http.StatusOK, map[string]any{"message": mode + " successful"})
}

// ── backup endpoints ──────────────────────────────────────────────────────────

// postDBBackup creates an explicit on-demand backup of whatsapp.db.
func postDBBackup(e *core.RequestEvent) error {
	if !dbeCheckDB(e) {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{"error": "DB Explorer not available"})
	}
	dbMu.Lock()
	name, err := dbeCreateBackup()
	dbMu.Unlock()
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	info, _ := os.Stat(filepath.Join(dbBackupDir, name))
	size := int64(0)
	if info != nil {
		size = info.Size()
	}
	return e.JSON(http.StatusOK, map[string]any{
		"name":    name,
		"size":    size,
		"message": "backup created",
	})
}

// getDBBackups lists all backup files in the backup directory.
func getDBBackups(e *core.RequestEvent) error {
	entries, err := os.ReadDir(dbBackupDir)
	if err != nil {
		if os.IsNotExist(err) {
			return e.JSON(http.StatusOK, map[string]any{"backups": []any{}})
		}
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	type backupInfo struct {
		Name    string `json:"name"`
		Size    int64  `json:"size"`
		Created string `json:"created"`
	}
	var backups []backupInfo
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".db") {
			continue
		}
		info, _ := entry.Info()
		size := int64(0)
		ts := ""
		if info != nil {
			size = info.Size()
			ts = info.ModTime().UTC().Format(time.RFC3339)
		}
		backups = append(backups, backupInfo{Name: entry.Name(), Size: size, Created: ts})
	}
	if backups == nil {
		backups = []backupInfo{}
	}
	return e.JSON(http.StatusOK, map[string]any{"backups": backups})
}

// postDBRestore restores whatsapp.db from a backup file, then fully reinitializes
// the whatsmeow stack so all in-memory state is rebuilt from the restored DB.
// Body: {"name": "whatsapp_20260316_143022.db"}
func postDBRestore(e *core.RequestEvent) error {
	if !dbeCheckDB(e) {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{"error": "DB Explorer not available"})
	}

	var req struct {
		Name string `json:"name"`
	}
	if err := json.NewDecoder(e.Request.Body).Decode(&req); err != nil {
		return apis.NewBadRequestError("invalid JSON body", err)
	}

	// Sanitize: no path traversal, only .db files in the backup directory
	if strings.ContainsAny(req.Name, "/\\") || strings.Contains(req.Name, "..") {
		return apis.NewBadRequestError("invalid backup name", nil)
	}
	if !strings.HasSuffix(req.Name, ".db") {
		return apis.NewBadRequestError("invalid backup name", nil)
	}
	backupPath := filepath.Join(dbBackupDir, req.Name)
	if _, err := os.Stat(backupPath); os.IsNotExist(err) {
		return apis.NewNotFoundError("backup not found", nil)
	}

	dbMu.Lock()
	defer dbMu.Unlock()

	// Close our connections so the file can be replaced
	if waDB != nil {
		_ = waDB.Close()
		waDB = nil
	}
	if waDBWrite != nil {
		_ = waDBWrite.Close()
		waDBWrite = nil
	}

	// Copy backup over the current DB file
	if err := dbeReplaceFile(backupPath, dbFilePath); err != nil {
		// Try to reopen connections even on failure
		_ = initDBExplorer(filePathToDSN(dbFilePath, "rwc"), "sqlite")
		return e.JSON(http.StatusInternalServerError, map[string]any{
			"error": fmt.Sprintf("restore failed: %v", err),
		})
	}

	// Reopen our connections
	if err := dbeReopenConnections(); err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{
			"error": fmt.Sprintf("restore succeeded but failed to reopen connections: %v", err),
		})
	}

	// Full reinitialize of the whatsmeow stack
	if err := whatsapp.Reinitialize(); err != nil {
		return e.JSON(http.StatusOK, map[string]any{
			"message":            "restore succeeded but whatsapp reinitialize failed",
			"reinitialize_error": err.Error(),
		})
	}

	return e.JSON(http.StatusOK, map[string]any{
		"message": "restore successful — whatsapp reinitialised from " + req.Name,
	})
}

// deleteDBBackup deletes a backup file.
func deleteDBBackup(e *core.RequestEvent) error {
	name := e.Request.PathValue("name")
	if strings.ContainsAny(name, "/\\") || strings.Contains(name, "..") {
		return apis.NewBadRequestError("invalid backup name", nil)
	}
	if !strings.HasSuffix(name, ".db") {
		return apis.NewBadRequestError("invalid backup name", nil)
	}
	path := filepath.Join(dbBackupDir, name)
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return apis.NewNotFoundError("backup not found", nil)
	}
	if err := os.Remove(path); err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	return e.JSON(http.StatusOK, map[string]any{"message": "backup deleted"})
}

// ── internal helpers ──────────────────────────────────────────────────────────

// dbeCreateBackup creates a clean copy of whatsapp.db using VACUUM INTO.
// Returns the backup filename (not full path). Caller must hold dbMu.
func dbeCreateBackup() (string, error) {
	if waDBWrite == nil {
		return "", fmt.Errorf("write connection not available")
	}
	if err := os.MkdirAll(dbBackupDir, 0o750); err != nil {
		return "", fmt.Errorf("create backup dir: %w", err)
	}
	name := fmt.Sprintf("whatsapp_%s.db", time.Now().UTC().Format("20060102_150405"))
	destPath := filepath.Join(dbBackupDir, name)
	// VACUUM INTO produces a clean, WAL-checkpointed copy. Path is internal — not user input.
	if _, err := waDBWrite.Exec(fmt.Sprintf(`VACUUM INTO %q`, destPath)); err != nil {
		return "", fmt.Errorf("VACUUM INTO: %w", err)
	}
	return name, nil
}

// dbeReplaceFile copies src over dst and removes any WAL/SHM sidecar files.
func dbeReplaceFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	if err := out.Sync(); err != nil {
		return err
	}

	// Remove WAL and SHM sidecars so SQLite starts fresh
	_ = os.Remove(dst + "-wal")
	_ = os.Remove(dst + "-shm")
	return nil
}

// dbeReopenConnections reopens both the read-only and read-write connections after a restore.
func dbeReopenConnections() error {
	roDSN := filePathToDSN(dbFilePath, "ro")
	db, err := sql.Open("sqlite", roDSN)
	if err != nil {
		return fmt.Errorf("reopen read-only: %w", err)
	}
	db.SetMaxOpenConns(1)
	waDB = db

	rwDSN := filePathToDSN(dbFilePath, "rwc")
	dbw, err := sql.Open("sqlite", rwDSN)
	if err != nil {
		return fmt.Errorf("reopen read-write: %w", err)
	}
	dbw.SetMaxOpenConns(1)
	waDBWrite = dbw
	return nil
}

// toReadOnlyDSN is kept for backward compatibility with any external callers.
func toReadOnlyDSN(dsn string) string {
	return filePathToDSN(extractFilePath(dsn), "ro")
}

// postDBQuery executes a read-only SQL query against the WhatsApp SQLite database.
// Only SELECT statements are allowed. Results are limited to 1000 rows.
func postDBQuery(e *core.RequestEvent) error {
	var body struct {
		SQL string `json:"sql"`
	}
	if err := e.BindBody(&body); err != nil {
		return e.JSON(http.StatusBadRequest, map[string]any{"error": "invalid body"})
	}

	stmt := strings.TrimSpace(body.SQL)
	if stmt == "" {
		return e.JSON(http.StatusBadRequest, map[string]any{"error": "sql is required"})
	}

	// Only allow SELECT statements
	upper := strings.ToUpper(stmt)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") && !strings.HasPrefix(upper, "EXPLAIN") {
		return e.JSON(http.StatusBadRequest, map[string]any{"error": "only SELECT/WITH/EXPLAIN statements are allowed"})
	}

	// Check that waDB is initialized
	if waDB == nil {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{"error": "whatsapp database not connected"})
	}

	start := time.Now()
	rows, err := waDB.QueryContext(e.Request.Context(), stmt+" LIMIT 1000")
	if err != nil {
		return e.JSON(http.StatusBadRequest, map[string]any{"error": err.Error()})
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}

	var result []map[string]interface{}
	for rows.Next() {
		vals := make([]interface{}, len(cols))
		ptrs := make([]interface{}, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			continue
		}
		row := make(map[string]interface{}, len(cols))
		for i, col := range cols {
			v := vals[i]
			if b, ok := v.([]byte); ok {
				row[col] = string(b)
			} else {
				row[col] = v
			}
		}
		result = append(result, row)
	}

	if result == nil {
		result = []map[string]interface{}{}
	}

	execMs := time.Since(start).Milliseconds()
	return e.JSON(http.StatusOK, map[string]any{
		"columns": cols,
		"rows":    result,
		"count":   len(result),
		"exec_ms": execMs,
	})
}
