package api

import (
	"database/sql"
	"encoding/hex"
	"fmt"
	"math"
	"net/http"
	"strconv"
	"strings"

	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
)

// waDB is a long-lived read-only connection to the whatsmeow SQLite file.
var waDB *sql.DB

// allowedTables is the hard-coded allowlist of whatsmeow tables exposed by the DB Explorer.
// Any table name not in this list returns 404.
var allowedTables = []string{
	"whatsmeow_device",
	"whatsmeow_identity_keys",
	"whatsmeow_pre_keys",
	"whatsmeow_sessions",
	"whatsmeow_sender_keys",
	"whatsmeow_app_state_sync_keys",
	"whatsmeow_app_state_version",
	"whatsmeow_app_state_mutation_macs",
	"whatsmeow_contacts",
	"whatsmeow_chat_settings",
	"whatsmeow_message_secrets",
	"whatsmeow_privacy_tokens",
}

var tableDescriptions = map[string]string{
	"whatsmeow_device":                  "Device identity: JID, Noise key, Identity key, Signed pre-key, Registration ID, platform, and server token. The core cryptographic identity of this WhatsApp session.",
	"whatsmeow_identity_keys":           "Signal Protocol identity keys for each known JID/device pair. Used to verify the long-term identity of contacts and detect security code changes.",
	"whatsmeow_pre_keys":                "One-time pre-keys generated by this device for Signal session initiation (X3DH key agreement). Each is consumed exactly once when a new session is established.",
	"whatsmeow_sessions":                "Signal Protocol Double Ratchet session state per contact/device. Contains serialized session data including chain keys, message keys, and ratchet counters.",
	"whatsmeow_sender_keys":             "Group SenderKey Distribution records. Each group member distributes a sender key so others can decrypt their messages without per-message key exchange.",
	"whatsmeow_app_state_sync_keys":     "Symmetric keys used to decrypt app state patches (contacts, settings, starred messages, labels, etc.) synced from the WhatsApp server.",
	"whatsmeow_app_state_version":       "Current version index and hash of each app state collection (critical, regular, critical_unblock_to_primary, etc.). Used for incremental sync.",
	"whatsmeow_app_state_mutation_macs": "HMAC integrity codes for individual app state mutations stored in the Merkle tree. Used to verify patch integrity during app state sync.",
	"whatsmeow_contacts":                "Known contacts with their push names and full names as synced from the WhatsApp server.",
	"whatsmeow_chat_settings":           "Per-conversation settings: mute expiry timestamp, pinned status, archived status.",
	"whatsmeow_message_secrets":         "Per-message secrets for media decryption and ephemeral (view-once) message handling.",
	"whatsmeow_privacy_tokens":          "Privacy tokens used when checking if phone numbers are registered on WhatsApp (contact availability check).",
}

// initDBExplorer opens a read-only SQL connection to the whatsmeow SQLite file.
// Only supported when dialect is "sqlite". Called once from api.Init.
func initDBExplorer(dsn, dialect string) error {
	if dialect != "sqlite" {
		pb.Logger().Warn("DB Explorer: only supported for sqlite dialect — skipping")
		return nil
	}
	if dsn == "" {
		pb.Logger().Warn("DB Explorer: empty DSN — skipping")
		return nil
	}
	roDSN := toReadOnlyDSN(dsn)
	db, err := sql.Open("sqlite", roDSN)
	if err != nil {
		return fmt.Errorf("db explorer: open read-only connection: %w", err)
	}
	db.SetMaxOpenConns(1)
	waDB = db
	pb.Logger().Info("DB Explorer: read-only connection established", "dsn", roDSN)
	return nil
}

// toReadOnlyDSN strips existing query params from a SQLite file URI and adds mode=ro.
func toReadOnlyDSN(dsn string) string {
	if !strings.HasPrefix(dsn, "file:") {
		return dsn
	}
	idx := strings.Index(dsn, "?")
	if idx >= 0 {
		return dsn[:idx] + "?mode=ro"
	}
	return dsn + "?mode=ro"
}

// isAllowedTable returns true if name is in the hard-coded allowlist.
func isAllowedTable(name string) bool {
	for _, t := range allowedTables {
		if t == name {
			return true
		}
	}
	return false
}

// getDBTables returns the list of allowed whatsmeow tables with their descriptions and row counts.
func getDBTables(e *core.RequestEvent) error {
	if waDB == nil {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{
			"error": "DB Explorer not available (sqlite only or not yet initialised)",
		})
	}

	type tableInfo struct {
		Name        string `json:"name"`
		Description string `json:"description"`
		Count       int64  `json:"count"`
	}

	tables := make([]tableInfo, 0, len(allowedTables))
	for _, t := range allowedTables {
		var count int64
		row := waDB.QueryRow(fmt.Sprintf("SELECT COUNT(*) FROM %q", t))
		_ = row.Scan(&count) // silently ignore if table doesn't exist yet
		tables = append(tables, tableInfo{
			Name:        t,
			Description: tableDescriptions[t],
			Count:       count,
		})
	}
	return e.JSON(http.StatusOK, map[string]any{"tables": tables})
}

// getDBTable returns paginated rows for a single allowed table.
// Query params: page (1-based), limit (1-200, default 50), filter (text search).
func getDBTable(e *core.RequestEvent) error {
	if waDB == nil {
		return e.JSON(http.StatusServiceUnavailable, map[string]any{
			"error": "DB Explorer not available (sqlite only or not yet initialised)",
		})
	}

	table := e.Request.PathValue("table")
	if !isAllowedTable(table) {
		return apis.NewNotFoundError("Table not found", nil)
	}

	// Parse query params
	page, _ := strconv.Atoi(e.Request.URL.Query().Get("page"))
	if page < 1 {
		page = 1
	}
	limit, _ := strconv.Atoi(e.Request.URL.Query().Get("limit"))
	if limit < 1 || limit > 200 {
		limit = 50
	}
	filter := e.Request.URL.Query().Get("filter")

	// Resolve column names via PRAGMA (trusted source — not user input)
	cols, err := dbeTableColumns(table)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	if len(cols) == 0 {
		return e.JSON(http.StatusOK, map[string]any{
			"table": table, "columns": []string{}, "rows": []any{},
			"page": 1, "limit": limit, "total": 0, "pages": 0,
		})
	}

	whereClause, filterArgs := dbeFilterClause(cols, filter)

	// Total count
	countSQL := fmt.Sprintf("SELECT COUNT(*) FROM %q %s", table, whereClause)
	var total int64
	if err := waDB.QueryRow(countSQL, filterArgs...).Scan(&total); err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}

	// Fetch page
	offset := (page - 1) * limit
	selectSQL := fmt.Sprintf("SELECT * FROM %q %s LIMIT ? OFFSET ?", table, whereClause)
	args := append(filterArgs, limit, offset)
	rows, err := waDB.Query(selectSQL, args...)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}
	defer rows.Close()

	data, err := dbeScanRows(rows, cols)
	if err != nil {
		return e.JSON(http.StatusInternalServerError, map[string]any{"error": err.Error()})
	}

	pages := int(math.Ceil(float64(total) / float64(limit)))
	if pages < 1 && total == 0 {
		pages = 0
	}

	return e.JSON(http.StatusOK, map[string]any{
		"table":   table,
		"columns": cols,
		"rows":    data,
		"page":    page,
		"limit":   limit,
		"total":   total,
		"pages":   pages,
	})
}

// dbeTableColumns returns the ordered list of column names for table via PRAGMA table_info.
func dbeTableColumns(table string) ([]string, error) {
	rows, err := waDB.Query(fmt.Sprintf("PRAGMA table_info(%q)", table))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var cols []string
	for rows.Next() {
		var cid int
		var name, typ string
		var notNull int
		var dfltVal sql.NullString
		var pk int
		if err := rows.Scan(&cid, &name, &typ, &notNull, &dfltVal, &pk); err != nil {
			return nil, err
		}
		cols = append(cols, name)
	}
	return cols, rows.Err()
}

// dbeFilterClause builds a safe WHERE clause from a free-text filter value.
// The filter value is passed exclusively as a bound parameter — never concatenated.
func dbeFilterClause(cols []string, filter string) (string, []any) {
	if filter == "" {
		return "", nil
	}
	like := "%" + filter + "%"
	parts := make([]string, len(cols))
	args := make([]any, len(cols))
	for i, col := range cols {
		parts[i] = fmt.Sprintf(`CAST("%s" AS TEXT) LIKE ?`, col)
		args[i] = like
	}
	return "WHERE (" + strings.Join(parts, " OR ") + ")", args
}

// dbeScanRows scans all rows into a slice of value slices.
// []byte values (binary blobs) are converted to lowercase hex strings.
func dbeScanRows(rows *sql.Rows, cols []string) ([][]any, error) {
	var result [][]any
	for rows.Next() {
		ptrs := make([]any, len(cols))
		vals := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return nil, err
		}
		row := make([]any, len(cols))
		for i, v := range vals {
			if b, ok := v.([]byte); ok {
				row[i] = hex.EncodeToString(b)
			} else {
				row[i] = v
			}
		}
		result = append(result, row)
	}
	return result, rows.Err()
}
